# Generated by Django 4.2 on 2025-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Telegram_id"
            ),
        ),
    ]
